name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-paas:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: action/checkout@v2

      - name: Academy transfers
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: academy-transfers # required
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL: https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: true # default: false

      - name: Push to GOV.UK PaaS
        run: cf push -b staticfile_buildpack academy-transfers-prototype
